### PR TITLE
Upgrade Jackson to latest version 2.8.8.

### PR DESCRIPTION
**Pull request by langfr**

### CODE REVIEW

**Comment by JoHeinem** [comment]
Hey @langfr ,

I posted a comment, which is also related to this issue here:
https://github.com/camunda/camunda-spin/pull/13

Best,
Johannes

**Comment by JoHeinem** [comment]
Hey @langfr ,

We have merged your PR.

Best,
Johannes

**Comment by JoHeinem** [comment]
Reverted PR. See comment camunda/camunda-spin#13.

**Comment by sdorokhova** [comment]
Hi @langfr ,
please be aware, that in latest alpha release (7.9.0-alpha2), we finally update Jackson version up to 2.9.3. Feel free to try it out.

Regards,
Svetlana

**Pull request closed without merging**
