### PR TITLE
json-path 2x

### PR DESCRIPTION
**Pull request by stefanzilske**
Related to #7

### CODE REVIEW

**Comment by ThorbenLindhauer** [comment]
Hi Stefan,

Thanks for your pull request. I found a couple of things that need to be changed before we can merge it:

* https://github.com/camunda/camunda-spin/pull/15/commits/693155c58093b723e794dae6cfefc0d9cdf33db2#diff-a7392837dfc2cdaabe12b11652083ae1: The Spin API should not throw a Jayway json-path exception; instead, that exception should wrapped in a `SpinJsonPathException`
* The json-smart library and its dependencies must be relocated to the `spinjar` namespace in the [camunda-spin-dataformat-all](https://github.com/camunda/camunda-spin/tree/master/dataformat-all) artifact.
* Please raise a pull request against https://github.com/camunda/camunda-bpm-platform that
  * updates the Spin version in [Camunda BOM](https://github.com/camunda/camunda-bpm-platform/tree/master/bom) to `1.4.0-SNAPSHOT`
  * creates Wildfly and JBoss modules for the new dependencies, [here](https://github.com/camunda/camunda-bpm-platform/tree/master/distro/wildfly/modules) and [here](https://github.com/camunda/camunda-bpm-platform/tree/master/distro/jbossas7/modules)

**Comment by stefanzilske** [comment]
@ThorbenLindhauer 

I added two commits to reflect your remarks. I will raise the PR to Camunda Platform asap ;)

Cheers,
Stefan

**Comment by ThorbenLindhauer** [comment]
Hi Stefan,

Thanks for the update. Package `org.objectweb` still needs relocation.

Cheers,
Thorben

**Comment by stefanzilske** [comment]
@ThorbenLindhauer 

oops, missed that one. Check my latest commit, now everything is relocated.

Cheers,
Stefan

**Comment by stefanzilske** [comment]
@ThorbenLindhauer 

I have prepared the changes to camunda-bpm-platform. Before I raise a PR, maybe you want to have a look at my latest commits on https://github.com/stefanzilske/camunda-bpm-platform, since I am not very familiar with creating JBoss modules...

Cheers,
Stefan

**Comment by ThorbenLindhauer** [comment]
Hi Stefan,

Please raise the pull request nevertheless. That makes it easier to review the code and it is absolutely no problem if it is not perfect yet.

Thanks,
Thorben

**Comment by stefanzilske** [comment]
OK - said and done: https://github.com/camunda/camunda-bpm-platform/pull/276

**Comment by ThorbenLindhauer** [comment]
Merged via https://github.com/camunda/camunda-spin/commit/46d5842627121413d61db420689a66fee9d69f4b.

**Pull request closed without merging**
