### PR TITLE
chore(xpath): throw exception for non existing elements, attributes

### PR DESCRIPTION
**Pull request by AlexMinsk**
-- throw meaningful exception for root node '/' expression
-- throw exception for non existing elements and attributes

related to CAM-3352

### CODE REVIEW

**Comment by AlexMinsk** [comment]
Hi Sebastian,

Please review changes.
Some comment from my side:

1. I didn't implement checkup of NonExisting nodes for builtin XPath functions string(), count() and boolean(), because it is not clear now if they are really needed:
   - element.xPath("string(/root/child/@nonExisting)").string();
   - element.xPath("count(/root/child/nonExisting)").number();
   - element.xPath("boolean(/root/nonExisting)").bool();

2. For element() and attribute() function checking of `/` expression with `if(ROOT_NODE_EXPRESSION.equals(expression))` can be done during ClassCastException not at the every beginning.

Br,
Alexander

**Comment by menski** [comment]
Hi Alexander,

thanks for the pull request. I will have a look at it today.

Cheers,
Sebastian

**Comment by menski** [comment]
Hi Alexander,

I had a look at your changes. I have some questions and remarks:

- I would think that the exception should be of type `SpinXPathException` as it is related to XPath
- There should be different exception messages for the root expression and not existing expression. I would suggest `XPath expression '/' not allowed` and `Unable to find XPath expression '{}'`.
- Why didn't you check for the `/` root expression for `elementList` and `attributeList`? They should behave the same.
- It would be nice if the test of `/` and null/empty would be in one place. Either in a method in the `DomXPathQuery` or in `DomXmlEnsure`. I would prefer latter. Maybe the following functions:
  - `ensureNotDocumentRootExpression(String expression)`
  - `ensureXPathNotNull(Node node)`
  - `ensureXPathNotEmpty(NodeList nodeList)` 

Other than that I like the change. Please let me know if you disagree with my suggestions. But I will be on vacation for the next week. So maybe there will be some delay in my answers.

Cheers,
Sebastian

**Comment by AlexMinsk** [comment]
Hi Sebastian,

Thanks for the review and tips. I will update code accordingly. 
About `elementList` and `attributeList`, I think I misunderstood something for theses functions, so I will add the check-up for `/`.

Br,
Alexander

**Comment by AlexMinsk** [comment]
Hi Sebastian,

Class `DomXmlEnsure` contains one method `ensureChildElement` which utilizes `elementIsNotChildOfThisElement(childElement, parentElement)` on `SpinLogger.CORE_LOGGER` to throw an exception. This method is used only in `DomXmlEnsure` class.

Maybe `elementIsNotChildOfThisElement(childElement, parentElement)` could be moved into `DomXmlLogger`, since it is more logically is not a core exception?

Br,
Alexander

**Comment by menski** [comment]
Hi Alex,

that sounds reasonable.

Cheers,
Sebastian

**Comment by AlexMinsk** [comment]
Hi,

so, I have one question.
In file `SpinCoreLogger` exception `elementIsNotChildOfThisElement` has id `005`.
When you are removing exceptions from the logger file, are you updating the numbering of remaining exceptions? So that all exceptions located under the deleted decrease their id by 1 (006 -> 005, 007 -> 006).

Br,
Alexander

**Comment by menski** [comment]
Hi,

no all release ids should stay the same. Just remove the exception. Thanks

Cheers,
Sebastian

**Comment by AlexMinsk** [comment]
Hi Sebastian,

I have created the 2nd commit, so you can see the latest changes.
I'm new in Git and if I need to do something special with these 2 commits, please tell me.

I didn't rewrite the test classes in part of loading validation strings from the xml files, because script's annotation elements want to be constants. Maybe it is better to leave this as is in order to have the same clean understanding of used validation xml strings both in `XmlDomXPathTest` and `XmlDomXPathScriptTest`.

Br,
Alexander

**Comment by menski** [comment]
Hi Alex,

thanks for the additional commit and sorry for the delay. I had already a look at it and its fine. I will merge it and squash the commits into one during this.

Cheers,
Sebastian

**Comment by menski** [comment]
Hi Alex,

I just merged your pull request (see 3c6b3c03676d14d1780bc1951096ca5cedd817f1). Thanks again for your contribution.

Cheers,
Sebastian

**Comment by AlexMinsk** [comment]
Hi Sebastian,

Thank you (and Camunda) that I have a chance to practice programming in well written projects.

Br,
Alexander

**Pull request closed without merging**
